---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-cni-plugins-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: cni-plugins
spec:
  template:
    metadata:
      labels:
        tier: node
        app: cni-plugins
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: cni-plugins
        image: quay.io/schseba/cni-plugins@sha256:e76ae2b1f393ea9056d9964c8664647f1c4afafcc0bfd949aacdc32f30b7b779
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /opt/cni/bin
      volumes:
      - name: cnibin
        hostPath:
          path: /opt/cni/bin
